- name: Create folder directory for inputs configuration
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - 'C:\Program Files\SplunkUniversalForwarder\etc\apps\powershell_inputs_app\local'

- name: Copy inputs.conf configuration
  win_copy:
    src: powershell_inputs.conf
    dest: 'C:\Program Files\SplunkUniversalForwarder\etc\apps\powershell_inputs_app\local\inputs.conf'
