
- include: install_splunk_uf.yml
- include: create_deploymentclient.yml
- include: configure_outputs.yml
- include: collect_powershell_logs.yml
- include: collect_attack_simulation_logs.yml
- include: collect_sysmon_logs.yml
- include: collect_windows_event_logs.yml
#- include: install_nxlog.yml

- name: Restart splunk
  win_command: splunk.exe restart
  args:
    chdir: C:\Program Files\SplunkUniversalForwarder\bin\
