- hosts: all
  gather_facts: True
  vars:
    ansible_connection: winrm
    ansible_port: 5986
#    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
#    ansible_winrm_read_timeout_sec: 600
  roles:
    - atomic_red_team
