- hosts: all
  gather_facts: False
  become: true
  vars:  
    hostname: splunk-server
  roles:
    - linux_common
    - search_head
    - splunk_phantom
    - splunk_phantom_configure
    - caldera
