---
- include: set-hostname.yml
- include: windows-disable-defender.yml
- include: windows-enable-ps-logging.yml
- include: windows-enable-4688-cmd-line-audit.yml
- include: windows-security-configure-logging.yml
