---
# Configure phantom with credentials, apps, assets, and so on...

- name: change phantom admin password
  uri:
    url: https://127.0.0.1/rest/user_settings
    method: POST
    user: admin
    password: password
    body: {"old_password":"password","password":"{{phantom_admin_password}}"}
    body_format: json
    force_basic_auth: yes
    validate_certs: no

- name: fetch phantom api token
  uri:
    url: https://127.0.0.1/rest/ph_user/2/token
    method: GET
    user: admin
    password: "{{phantom_admin_password}}"
    force_basic_auth: yes
    validate_certs: no
  register: api_token

- name: display phantom api token
  debug:
    msg: "phantom api token is {{api_token.json.key}}"

- name: open up api allowed ip list
  uri:
    url: https://127.0.0.1/rest/ph_user/2
    method: POST
    body: '{"allowed_ips":["any"]}'
    user: admin
    password: "{{phantom_admin_password}}"
    force_basic_auth: yes
    validate_certs: no

- name: test api token
  uri:
    url: https://127.0.0.1/rest/container
    method: GET
    return_content: yes
    headers:
      ph-auth-token: "{{api_token.json.key}}"
    validate_certs: no

# install a list of apps using RPMs. URL's can be found at https://repo.phantom.us/phantom/4.8/apps/x86_64/

- name: install whois app
  yum:
    name: http://repo.phantom.us/phantom/4.8/apps/x86_64/phantom_whois-1.2.41.x86_64.rpm
    state: present

- name: install maxmind app
  yum:
    name: https://repo.phantom.us/phantom/4.8/apps/x86_64/phantom_maxmind-2.0.3.x86_64.rpm
    state: present

- name: install dns app
  yum:
    name: https://repo.phantom.us/phantom/4.8/apps/x86_64/phantom_dns-1.3.32.x86_64.rpm
    state: present

- name: install phishtank app
  yum:
    name: https://repo.phantom.us/phantom/4.8/apps/x86_64/phantom_phishtank-1.0.21.x86_64.rpm
    state: present

- name: install splunk app
  yum:
    name: https://repo.phantom.us/phantom/4.8/apps/x86_64/phantom_splunk-1.3.41.x86_64.rpm
    state: present

- name: install winrm app
  yum:
    name: https://repo.phantom.us/phantom/4.8/apps/x86_64/phantom_winrm-1.0.19.x86_64.rpm
    state: present

# template to install more apps
#- name: install <> app
#  yum:
#    name:
#    state: present
